min_fastlane_version("2.73.0")

default_platform(:ios)

platform(:ios) do
  desc "Runs all the tests"
  lane :test do
  end

  desc "Submit a new beta build to App Store Connect"
  lane :beta do
    # Download signing credentials
    sync_code_signing(readonly: true)
    
    # Set the build number to the number of Git commits
    build_number = sh "git log --oneline | wc -l"
    increment_build_number(build_number: build_number)

    # Set the marketing number to the release branch name
    release_branch = ENV['CI_COMMIT_BRANCH']
    match = /release\/(.*)/.match(release_branch)
    unless match.nil?
      increment_version_number(version_number: match[1])
    end

    # Build the app for App Store
    build_app(
      export_method: "app-store",
      scheme: "Debigulator")
    
    # Just upload the build to App Store Connect, no other changes
    upload_to_testflight(
      api_key_path: ENV["APPLE_API_KEY_JSON"],
      app_platform: "ios",
      skip_submission: true,
      skip_waiting_for_build_processing: true)
  end
end
